### PR TITLE
Editable Main Menu!

### PR DESCRIPTION
**Pull request by MasterDirector99**
Thanks to @RafaelGiacom for the code! I was able to port it in Modding+!

(Please merge this request.)

### CODE REVIEW

**Comment by MasterDirector99** [comment]
I hope it doesn't fail.

**Comment by RafaelGiacom** [comment]
can you close this one? my pull request of ng text already has it

**Comment by MasterDirector99** [comment]
Ok.

**Comment by MasterDirector99** [comment]
I'm sorry, @RafaelGiacom.

**Comment by MasterDirector99** [comment]
I can't close it now because you still trying to fix the NG Text.

**Comment by MasterDirector99** [comment]
Closed as Raf reverted the changes!

**Pull request closed without merging**
